// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BJKBtrSJUSgSz1p1gZMJHDpOG46IYhI',
    appId: '1:268084278002:web:b071c7a35869d0c96e566b',
    messagingSenderId: '268084278002',
    projectId: 'auction-fyp',
    authDomain: 'auction-fyp.firebaseapp.com',
    databaseURL: 'https://auction-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auction-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXiTsuPNSr57YHjO-2KYY_rrRTYqOgVQ',
    appId: '1:268084278002:android:4652ebe7865978ba6e566b',
    messagingSenderId: '268084278002',
    projectId: 'auction-fyp',
    databaseURL: 'https://auction-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auction-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmV_PUJD5SLO3WZv7hRRWzOflhM8b6aE',
    appId: '1:268084278002:ios:8f9caaa8029253306e566b',
    messagingSenderId: '268084278002',
    projectId: 'auction-fyp',
    databaseURL: 'https://auction-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auction-fyp.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmV_PUJD5SLO3WZv7hRRWzOflhM8b6aE',
    appId: '1:268084278002:ios:8f9caaa8029253306e566b',
    messagingSenderId: '268084278002',
    projectId: 'auction-fyp',
    databaseURL: 'https://auction-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auction-fyp.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BJKBtrSJUSgSz1p1gZMJHDpOG46IYhI',
    appId: '1:268084278002:web:bf45c5d68e73f1126e566b',
    messagingSenderId: '268084278002',
    projectId: 'auction-fyp',
    authDomain: 'auction-fyp.firebaseapp.com',
    databaseURL: 'https://auction-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auction-fyp.firebasestorage.app',
  );
}
